
tasks:
  -
    name: KaliDAO Subgraph
    init: |
      eval $(gp env -e)
      yarn install
      yarn prepare:goerli
      yarn codegen
      yarn build

vscode:
  extensions:
    - esbenp.prettier-vscode
    - GraphQL.vscode-graphql
